# Generated by Django 5.1.5 on 2025-02-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='comodidades',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas',
        ),
        migrations.CreateModel(
            name='Comodidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comodidades_set', to='clientes.estacionamento')),
            ],
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='comodidades',
            field=models.ManyToManyField(blank=True, related_name='estacionamentos', to='clientes.comodidade'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='vagas',
            field=models.ManyToManyField(blank=True, to='clientes.vaga'),
        ),
    ]
