# Generated by Django 5.1.5 on 2025-02-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_vaga_remove_estacionamento_comodidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
    ]
