# Generated by Django 5.1.5 on 2025-02-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_endereco_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodidade',
            name='estacionamento',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='comodidades',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Comodidade',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Estacionamento',
        ),
        migrations.DeleteModel(
            name='Vaga',
        ),
    ]
