# Generated by Django 4.2.19 on 2025-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0002_remove_estacionamento_comodidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
