# Generated by Django 5.1.5 on 2025-02-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0003_remove_estacionamento_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='comodidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='estacionamentos', to='estacionamentos.comodidade'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='data_hora_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='data_hora_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamentos.endereco'),
        ),
    ]
