# Generated by Django 4.2.19 on 2025-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0003_remove_estacionamento_vagas_estacionamento_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodidade',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='comodidade',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='comodidade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comodidade',
            name='tipo',
        ),
        migrations.AddField(
            model_name='comodidade',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
