# Generated by Django 5.1.5 on 2025-02-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0004_alter_endereco_cep_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='data_hora_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='data_hora_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
