# Generated by Django 4.2.19 on 2025-02-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0004_remove_comodidade_cep_remove_comodidade_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='estacionamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamento_set', to='estacionamentos.estacionamento'),
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='comodidades',
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamentos', to='estacionamentos.endereco'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='comodidades',
            field=models.ManyToManyField(blank=True, related_name='estacionamentos', to='estacionamentos.comodidade'),
        ),
    ]
