# Generated by Django 4.2.19 on 2025-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0005_endereco_estacionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='endereco',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
