# Generated by Django 4.2.19 on 2025-02-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0006_remove_estacionamento_endereco_estacionamento_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamento',
            old_name='vagas',
            new_name='vagas_disponiveis',
        ),
    ]
