# Generated by Django 4.2.19 on 2025-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0009_remove_estacionamento_vagas_estacionamento_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas_disponiveis',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
