# Generated by Django 4.2.19 on 2025-02-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0010_remove_estacionamento_vagas_disponiveis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='vagas',
            field=models.ManyToManyField(blank=True, related_name='estacionamentos', to='estacionamentos.vaga'),
        ),
    ]
