# Generated by Django 4.2.19 on 2025-02-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0012_remove_estacionamento_vagas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
