# Generated by Django 4.2.19 on 2025-02-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0015_remove_estacionamento_vagas_estacionamento_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='vagas_disponiveis',
        ),
    ]
